version: '3.8'  # Specifies the Docker Compose file format version.

services:
  spring-dockerized-app:
    build:
      context: .  # Directory to build Docker image from.
      dockerfile: Dockerfile  # Dockerfile to use for building the image.
    ports:
      - 18080:8080  # Maps port 8080 in the container to port 18080 on the host.
    depends_on:
      mysqldb:
        condition: service_healthy  # Waits for 'mysqldb' to be healthy before starting.
    env_file:
      - .env  # Loads environment variables from the .env file.
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}  # Database URL.
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}  # Database username.
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}  # Database password.
      - SPRING_CONFIG_LOCATION=file:/app/application.properties  # Location of application properties.
    networks:
      - springboot-mysql-network  # Connects to the specified network.
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties  # Mounts properties file.

  adminer_client:
    image: adminer:4.8.1-standalone
    container_name: adminer_client
    hostname: adminer_client
    networks:
      - springboot-mysql-network  # Connects to the specified network.
    restart: always
    depends_on:
      - mysqldb
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    ports:
      - 28080:8080

  mysqldb:
    image: mysql:8.0.39  # MySQL image version.
    ports:
      - 13306:3306  # Maps port 3306 in the container to port 13306 on the host.
    env_file:
      - .env  # Loads environment variables from the .env file.
    volumes:
      - mysql-data:/var/lib/mysql  # Persistent storage for MySQL data.
      # - ./src/main/resources/db_migration/init_all.sql:/docker-entrypoint-initdb.d/init.sql  # Initialization script.
    networks:
      - springboot-mysql-network  # Connects to the specified network.
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]  # Health check command.
      retries: 10  # Number of retries before considering the service unhealthy.
      interval: 3s  # Time between retries.
      timeout: 30s  # Timeout for each health check.

volumes:
  mysql-data:  # Named volume for MySQL data.

networks:
  springboot-mysql-network:
    name: springboot-mysql-network  # Custom network for service communication.